blank_issues_enabled: false
contact_links:
    - name: ğŸ“– é—®é¢˜åé¦ˆæŒ‡å— / Troubleshooting Guide
      url: https://github.com/MaaEnd/MaaEnd/blob/main/docs/users/troubleshooting.md
      about: æäº¤ Issue å‰è¯·å…ˆé˜…è¯»æ­¤æ–‡æ¡£ / Please read this guide before submitting an issue
    - name: ğŸ§ ç”¨æˆ· QQ ç¾¤ / User QQ Group (1062010346)
      url: https://qm.qq.com/q/AmfJpePrI6
      about: ç•…èŠä½¿ç”¨å¿ƒå¾—ã€æå‡ºå»ºè®®ç­‰ / Chat about usage, share ideas, etc.
    - name: ğŸ§ å¼€å‘ QQ ç¾¤ / Dev QQ Group (1072587329)
      url: https://qm.qq.com/q/etmHz614fm
      about: å¹²æ´»ç¾¤ï¼Œæ¬¢è¿åŠ å…¥ä¸€èµ·å¼€å‘ï¼Œä½†ä¸å—ç†ç”¨æˆ·é—®é¢˜ / Development discussions only
